#!/bin/bash

runDig() {
    local subarg="$1"
    local urlarg="$2"

    dig "$subarg.$urlarg" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subarg" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

processSingleSubdomain() {
    local url="$1"
    local sub="$2"
    runDig "$sub" "$url"
}

processAllSubdomains() {
    local url="$1"
    local allSubs=("www" "lb-01" "web-01" "web-02")

    for s in "${allSubs[@]}"; do
        runDig "$s" "$url"
    done
}

main() {
    if [ $# -eq 1 ]; then
        local url="$1"
        processAllSubdomains "$url"
    elif [ $# -eq 2 ]; then
        local url="$1"
        local sub="$2"
        processSingleSubdomain "$url" "$sub"
    else
        echo "Usage: $0 <url> [subdomain]"
        exit 1
    fi
}

main "$@"

