#!/usr/bin/env bash
# Write a Bash script that transfers 
# a file from our client to a server

if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  if [ ! -f "$1" ]; then
    echo "'$1' file not found."
    exit 1
  fi

  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi

