#!/bin/env bash
# install nginx and start it 

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER:$USER" /var/www/html/index.nginx-debian.html
chmod -R 755 /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
service nginx restart

