#!/bin/env bash
# install nginx and start it 

sudo apt-get -y updatey
sudo apt-get -y install nginxy
sudo ufw allow 'Nginx HTTP'
chmod -R 755 /var/www/index.nginx-debian.html
sudo chown -R "$USER:$USER" /var/www/html/index.nginx-debian.html
echo "Hello Wrold!" > index.nginx-debian.html
service nginx restart

