#!/usr/bin/env bash
# replice the service

sudo apt-get -y update
sudo apt-get -y install nginx
#sudo wget -q -O /etc/nginx/sites-available/default http://example.com/static/raw/nginx/ubuntu20.04/etc/nginx/sites-available/default
path="/etc/nginx/sites-available/default"
sudo sh -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' $path
sudo sed -i '/^}$/i \ \n\tlocation @404 {return 404 "Ceci n'\''est pas une page\\n";}' $path
sudo sed -i 's/=404/@404/g' $path
sudo sed -i "0,/location \/ {/s/location \/ {/&\n\t\tadd_header X-Served-By '$HOSTNAME';/" $path
sudo service nginx restart
