#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver 429606-web-01 52.87.255.164:80 check\n\tserver 429606-web-02	18.204.11.196:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
