#!/usr/bin/env bash
# Bash script that generates a MySQL 
# dump and creates a compressed archive out of it.
mysqldump -uroot -p"$1" --all-databases > backup.sql
current_date=$(date "+%d-%m-%Y")
tar -cvzf "$current_date.tar.gz" backup.sql

