#!/bin/bash

# Bash script that generates a MySQL 
# dump and creates a compressed archive out of it.
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <mysql_password>"
    exit 1
fi

mysqldump -u root -p"$1" --all-databases > backup.sql
current_date=$(date "+%d-%m-%Y")
tar -czf "$current_date.tar.gz" backup.sql
