#!/usr/bin/env bash
#To file, or not to file 

if [ -e "school" ];then
    echo "school file exists"
    if [ ! -s "school" ];then
        echo "school file is empty"
    else 
        echo "school file is not empty"
    fi
    if [ -f "school" ];then
        echo "school is a regular file"
    fi
elif [ ! -e "school" ];then
    echo "school file does not exist"
fi